baseURL = "https://blog.ngot.me/"
languageCode = "en-us"
DefaultContentLanguage = "cn"
title = "Henry's blog"
publishDir = "../docs"
theme = "yinyang"

enableRobotsTXT = true
canonifyURLs = true

[params]
disqus = "ngot"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132840562-1"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js", new Date());gtag("config", "UA-132840562-1");</script>'

[[params.socials]]
name = "About Me"
link = "https://ngot.me"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2

[author]
  name = "Henry Zhuang"
  homepage = "https://ngot.me/"
